### PR TITLE
Keep unencrypted addon config for jwt-aware addons if jwt is present

### PR DESCRIPTION
**Pull request by BanzaiMan**
This is basically a port of
https://github.com/travis-ci/travis-scheduler/pull/34 to scheduler-2.

See that PR for rationale.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Tested in staging.

1. push build: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/514005
1. PR build from a fork, with sauce connect and JWT: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/514017
1. PR build from a fork, with sauce connect, but without JWT: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/514021

The second one shows (https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/514017#L224) that the JWT token (which is a secret here: https://github.com/BanzaiMan/travis_staging_test/blob/82298eb9bb3c5316866ffb5916824f7ef143c4f5/.travis.yml#L18-L19) is exposed.

**Comment by BanzaiMan** [comment]
@svenfuchs For review. :-D

**Comment by svenfuchs** [comment]
@BanzaiMan the code looks good to me. 

Just to confirm, the JWT addon in `travis-build` overwrites/replaces `SAUCE_ACCESS_KEY` in the env?

Have you tried `cat`ing the build script itself? The script will include the original `SAUCE_ACCESS_KEY` as passed to the worker, won't it? Does `travis-build` modify the build script? 

Also, do we have to worry about the bash history? Will the original key be in memory and could somehow be dumped?

**Comment by BanzaiMan** [comment]
@svenfuchs 

The JWT addon exports *only* the JWT itself to the build script. https://github.com/travis-ci/travis-build/blob/c29f71bdecaaf91fcf3df8fc51cde745dce256bd/lib/travis/build/addons/jwt.rb#L33. The build VM does not have access to the secret, only the JWT, which the script cannot verify (but can decode, but the payload itself is public https://github.com/travis-ci/travis-build/blob/c29f71bdecaaf91fcf3df8fc51cde745dce256bd/lib/travis/build/addons/jwt.rb#L15-L21). I do not think bash history is going to be a problem here.

**Comment by svenfuchs** [comment]
Ahh, that makes sense. Thanks for clearing this up, @BanzaiMan :heart:

**Comment by BanzaiMan** [comment]
@tjenkinson Sauce Connect addon is not activated on PR builds from forks.

**Pull request merged**
