### PR TITLE
Enterprise capacity

### PR DESCRIPTION
**Pull request by GbArc**
Currently can't run builds on private repos in enterprise builds since there are no plans/subscriptions per user. 
Prepared a new 'enterprise' capability depending on config.enterprise setting. 

Please let me know if there's an easier approach/config option to set

### CODE REVIEW

**Comment by svenfuchs** [comment]
@GbArc do i understand this right that on enterprise capacity is unlimited no matter the user? is that true for every customer?

**Comment by GbArc** [comment]
yes, theres no users/plans management for enterprise, at least for now. In enterprise an user can be only suspended

**Comment by svenfuchs** [comment]
in that case it seems like a bit of a waste to run through all capacities only to unconditionally accept the job in the end.

how about we change https://github.com/travis-ci/travis-scheduler/blob/7acb1504fafaad266b6817c593e33cc7d5b3dc85/lib/travis/scheduler/jobs/capacities.rb#L25 to something like:

```ruby
        def accept(job)
          enterprise? ? true : all.detect { |capacity| capacity.accept?(job) }
        end

          # end of the class body
          def applicable?
            config[:enterprise]
          end
```

**Comment by GbArc** [comment]
much easier and works ok, but i'm curious if it won't break something since there's no applicable/report/exhausted etc. anymore?

**Pull request merged**
