### PR TITLE
Re-raise exceptions after reaching a threshold

### PR DESCRIPTION
**Pull request by meatballhat**
which is intended to handle the case where an error condition is hit that cannot
be resolved in-process, e.g.: https://www.traviscistatus.com/incidents/pqwwl10y5xc9

### CODE REVIEW

**Comment by meatballhat** [comment]
@svenfuchs The error does not appear to be related to this PR, fwiw, but I'm unsure of how you'd prefer it to be resolved.

**Comment by meatballhat** [comment]
@svenfuchs I think I know what's going on.  It's related to a recent change in the postgresql addon.

**Comment by svenfuchs** [comment]
@meatballhat thanks for looking into this!

What's the intention of re-raising the error? Stopping and restarting the service? I believe bubbling the error up will break the `run_periodically` loop and stop the service, so that it would (I think) be restarted by Heroku. (We're using Bunny for talking to RabbitMQ, which doesn't block, right?)

As for the actual error, I see this in the incident:

```
PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT "jobs".* FROM "jobs"  WHERE "jobs"."state" = 'created' ORDER BY jobs.id
```

What's the recent change in the postgresql addon? Or do you mean the `pg` gem?

**Comment by meatballhat** [comment]
@svenfuchs My intent with re-raising the error is indeed to allow the process supervisor to restart the process.

I'm sorry for causing confusion with the postgresql addon comment.  I was referring to the way the postgresql addon works in `travis-build` wrt `bundle exec rake db:create --trace`.  It seems that the previous behavior when using `addons.postgresql` for certain versions of PostgreSQL required explicit creation of the `travis` database, which is no longer the case.

As for the `PG::ConnectionBad` error, I can only guess about what it really means or what's causing it, and it seems to have been a perplexing issue in the past for others: https://discussion.heroku.com/t/postgresql-dev-connections-are-all-pooching-a-lot/862

**Comment by meatballhat** [comment]
@svenfuchs any interest in this?

**Pull request closed without merging**
