### PR TITLE
Upgrade Ruby to 2.6.5

### PR DESCRIPTION
**Pull request by clekstro**
This updates scheduler in a similar fashion to how we recently updated API in https://github.com/travis-ci/travis-api/pull/1056.

On Heroku, we need to ensure that before we deploy that we've added/enabled the jemalloc buildpack:

```bash
heroku buildpacks:add --index 1 https://github.com/gaffneyc/heroku-buildpack-jemalloc.git -a <app_name>
heroku config:set JEMALLOC_ENABLED=true -a <app_name>
```

Using Docker, this updates the version and adds the `libjemalloc-dev` packages and sets the `LD_PRELOAD` ENV var so that Ruby uses jemalloc without any need for the gem.

### CODE REVIEW

**Comment by eugene-travis** [comment]
looks like conflicts with https://github.com/travis-ci/travis-scheduler/pull/218/files

**Comment by clekstro** [comment]
@eugene-travis indeed, though I think this should take precedence so we have a unified Ruby version across apps. Beyond the Ruby version, I think the only conflict is that you're using Bionic during the quay step, correct? I can add that to this PR if it's necessary.

**Comment by eugene-travis** [comment]
> I think the only conflict is that you're using Bionic during the quay step, correct? I can add that to this PR if it's necessary.
yes xenial spoils image with old libssl link in puma (do not understand yet why)

**Comment by eugene-travis** [comment]
I wonder if that https://github.com/travis-ci/travis-scheduler/blob/master/.ruby-version should be also updated.

**Comment by eugene-travis** [comment]
when can we merge it?

**Comment by clekstro** [comment]
@eugene-travis I want to test it on staging first before we merge. If I don't get to it later this afternoon, then I'll have a look in the morning.

**Comment by eugene-travis** [comment]
@clekstro ping.

**Pull request merged**
