### PR TITLE
JWT addon support for the BROWSERSTACK_ACCESS_KEY environment variable.

### PR DESCRIPTION
**Pull request by pulkitsharma07**
We have implemented the changes required to support JWT on our infrastructure.

### CODE REVIEW

**Comment by pulkitsharma07** [comment]
@BanzaiMan , could you please review this ?

**Comment by nakula** [comment]
hey @svenfuchs @joshk can guys look into this pull request once.

**Comment by caitlinrubin-optimizely** [comment]
Hi we're waiting on this merge over at Optimizely -- any word on when this will be completed and available for use? Thank you.

**Comment by BanzaiMan** [comment]
Sorry for the delay. Right now, we are reevaluating the JWT support implementation. Thank you for your patience.

@pulkitsharma07 Please email us at support@travis-ci.com.

**Comment by caitlinrubin-optimizely** [comment]
Any updates on this?

**Comment by caitlinrubin-optimizely** [comment]
Hi - we're still waiting on this! Any updates?

**Comment by pulkitsharma07** [comment]
@caitlinrubin-optimizely , we are setting up a call with Travis regarding this. Unfortunately, I do not have any other updates to share as of now.

You can mail us at support@browserstack.com for any queries.

Thanks !

**Comment by praveen31** [comment]
Travis has informed us that the JWT protocol will be deprecated in the future, and hence our PR will not be merged.

**Comment by nijel** [comment]
That's unfortunate, is there some other solution planned to make testing of PRs possible without exposing token to everybody?

**Comment by pulkitsharma07** [comment]
No, there is no way which guarantees a 100% secure way to test PRs as of now for BrowserStack.

There are some workarounds like encoding the BrowserStack credentials in the `.travis.yml` file (so that they are not visible in plaintext or indexed by Github) and then decoding them before the variables are injected for a travis build.

But this is not secure, as they can be easily intercepted by a "rogue" PR, which can access the decoded environment variables and print them to the console.

**Comment by nijel** [comment]
Thanks, I'm aware of that and that's why I found the usage of one time tokens really good fit for this purpose.

**Pull request closed without merging**
