### PR TITLE
https urls in gemfile, bundle update (second attempt)

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**
There were issues leading to the revert of https://github.com/travis-ci/travis-scheduler/pull/49

This is the PR tracking the second attempt of getting this working.

### CODE REVIEW

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
The errors I got were:

```
2016-10-31T17:37:25.614844+00:00 app[sidekiq.1]: 9 TID-ov9uqhsfk WARN: {"queue":"scheduler-2","class":"Travis::Scheduler::Worker","args":["event","job:finished",{"id":172051326}],"expires_in":300,"retry":true,"jid":"57209d7d5dde02e49bcfe6bf","created_at":1477935445.6129355,"expires_at":1477935745.6129718,"enqueued_at":1477935445.6130269,"error_message":"can not use unregistered object \"event\". known objects are: [:notify]","error_class":"RuntimeError","failed_at":1477935445.6129544,"retry_count":0}
2016-10-31T17:37:25.614896+00:00 app[sidekiq.1]: 9 TID-ov9uqhsfk WARN: RuntimeError: can not use unregistered object "event". known objects are: [:notify]
2016-10-31T17:37:25.614943+00:00 app[sidekiq.1]: 9 TID-ov9uqhsfk WARN: /app/lib/travis/support/registry.rb:9:in `[]'
2016-10-31T17:37:25.614945+00:00 app[sidekiq.1]: /app/lib/travis/scheduler/services.rb:8:in `[]'
2016-10-31T17:37:25.614946+00:00 app[sidekiq.1]: /app/lib/travis/scheduler/worker.rb:9:in `perform'
2016-10-31T17:37:25.614947+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:152:in `execute_job'
2016-10-31T17:37:25.614947+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'
2016-10-31T17:37:25.614948+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
2016-10-31T17:37:25.614949+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/metriks-0.9.9.7/lib/metriks/timer.rb:51:in `call'
2016-10-31T17:37:25.614949+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/metriks-0.9.9.7/lib/metriks/timer.rb:51:in `time'
2016-10-31T17:37:25.614950+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/bundler/gems/travis-metrics-37eac93bd1e9/lib/travis/metrics/sidekiq.rb:7:in `call'
2016-10-31T17:37:25.614951+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2016-10-31T17:37:25.614951+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
2016-10-31T17:37:25.614952+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2016-10-31T17:37:25.614953+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
2016-10-31T17:37:25.614953+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2016-10-31T17:37:25.614954+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2016-10-31T17:37:25.614954+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/logging.rb:32:in `with_context'
2016-10-31T17:37:25.614955+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2016-10-31T17:37:25.614956+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2016-10-31T17:37:25.614956+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `call'
2016-10-31T17:37:25.614957+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2016-10-31T17:37:25.614957+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:129:in `block in process'
2016-10-31T17:37:25.614958+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:168:in `stats'
2016-10-31T17:37:25.614959+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:128:in `process'
2016-10-31T17:37:25.614959+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:80:in `process_one'
2016-10-31T17:37:25.614960+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:68:in `run'
2016-10-31T17:37:25.614960+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:17:in `watchdog'
2016-10-31T17:37:25.614974+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
The PR downgraded `sidekiq`, and several other gems. Looking into fixing that now.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
This has been updated to only upgrade.

**Comment by ffffux** [comment]
See Igor's [Slack message with details](https://travisci.slack.com/archives/teal/p1477999623004870). Assigning @svenfuchs for Scheduler for now.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
`redlock` is still being downgraded for some reason. :-/

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
fixed via ruby version update to 2.3.1

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Failing test case is likely due to a change in travis-rollout.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Rolling that dep back to previous version.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Closing since this should now be merged into master.

**Pull request closed without merging**
